export const words = [
  'creativity',
  'developer',
  'frontend',
  'persistent',
  'Madelen',
  'sketch',
  'frontend ',
  'ui/ux',
  'interaction',
  'creativity',
  'developer',
  'frontend',
  'persistent',
  'Madelen',
  'sketch',
  'frontend ',
  'ui/ux',
  'interaction',
  'creativity',
  'developer',
  'frontend',
  'persistent',
  'Madelen',
  'sketch',
  'frontend ',
  'ui/ux',
  'interaction',
  'creativity',
  'developer',
  'frontend',
  'persistent',
  'Madelen',
  'sketch',
  'frontend ',
  'ui/ux',
  'interaction',
  'creativity',
  'developer',
  'frontend',
  'persistent',
]
